name: modular-painting
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python >=3.6
  - biopython
  - numpy
  - pandas >=1
  - blast >=2.10
  - python-igraph
  - mappy
  - matplotlib
  - bokeh >=1.4
  - pip
  - pip:
      - -e .
