name: test

on: push
jobs:
  Test-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: Pull repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install .
      - name: Test package
        run: pytest tests/*.py
